<a href="https://colab.research.google.com/github/ARJUN108-verma/Demo/blob/main/tensors_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Customization basics: tensors and operations

In [14]:
import tensorflow as tf

In [15]:
#tensors
print(tf.math.add(2,3))
print(tf.math.add([2,3],[4, 5]))
print(tf.math.square(5))
print(tf.math.reduce_sum([1,2,3,4]))

# Operator overloading is also supported
print(tf.math.square(3) + tf.math.square(4))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([6 8], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)


In [16]:
x = tf.linalg.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


Numpy

In [17]:
import numpy as np
ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.math.multiply(ndarray, 42)
print(tensor)

print("And Numpy operation convert tensors to numpy automatically ")
print(np.add(tensor, 1))

print("the .numpy(method explicitly converts a tensor to numpy")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And Numpy operation convert tensors to numpy automatically 
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
the .numpy(method explicitly converts a tensor to numpy
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


GPU Acceleration

In [18]:
tf.random.uniform([3, 3])
print("Is there is GPU available : "),
print(tf.config.list_physical_devices("GPU"))

print("Is the tensor on GPU  #0 :")
print(x.device.endswith('GPU:0'))

Is there is GPU available : 
[]
Is the tensor on GPU  #0 :
False


Device names

Explicit device placement

In [19]:
import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.linalg.matmul(x, x)

  result = time.time()-start

  print("10 loops: {:0.2f}ms".format(1000*result))

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith("CPU:0")
  time_matmul(x)

# Force execution on GPU #0 if available
if tf.config.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("GPU:0")
    time_matmul(x)

On CPU:
10 loops: 442.23ms


Datasets

Create a source Dataset

In [20]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

Apply transformations

In [21]:
ds_tensors = ds_tensors.map(tf.math.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

Iterate

In [22]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  4], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
